# Generated by Django 3.2.2 on 2021-06-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210614_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mal_requirements',
            options={'managed': True, 'verbose_name': 'Mal Requirement', 'verbose_name_plural': 'Mal Requirements'},
        ),
    ]
